# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clipboard_QT.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(543, 473)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(543, 473))
        MainWindow.setMaximumSize(QtCore.QSize(543, 473))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bk_pic/clipboard_refresht.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#MainWindow{background: url(:/bk_pic/post-bg-desk.jpg)}")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.EditBox_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.EditBox_1.setGeometry(QtCore.QRect(10, 10, 421, 111))
        self.EditBox_1.setObjectName("EditBox_1")
        self.CopyButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.CopyButton_1.setGeometry(QtCore.QRect(460, 30, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.CopyButton_1.setFont(font)
        self.CopyButton_1.setObjectName("CopyButton_1")
        self.EditBox_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.EditBox_2.setGeometry(QtCore.QRect(10, 150, 421, 111))
        self.EditBox_2.setObjectName("EditBox_2")
        self.EditBox_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.EditBox_3.setGeometry(QtCore.QRect(10, 290, 421, 111))
        self.EditBox_3.setObjectName("EditBox_3")
        self.CopyButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.CopyButton_2.setGeometry(QtCore.QRect(460, 180, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.CopyButton_2.setFont(font)
        self.CopyButton_2.setObjectName("CopyButton_2")
        self.CopyButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.CopyButton_3.setGeometry(QtCore.QRect(460, 330, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.CopyButton_3.setFont(font)
        self.CopyButton_3.setStatusTip("")
        self.CopyButton_3.setObjectName("CopyButton_3")
        self.ClearButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton_1.setGeometry(QtCore.QRect(460, 70, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.ClearButton_1.setFont(font)
        self.ClearButton_1.setObjectName("ClearButton_1")
        self.ClearButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton_2.setGeometry(QtCore.QRect(460, 220, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.ClearButton_2.setFont(font)
        self.ClearButton_2.setObjectName("ClearButton_2")
        self.ClearButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton_3.setGeometry(QtCore.QRect(460, 370, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.ClearButton_3.setFont(font)
        self.ClearButton_3.setObjectName("ClearButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setStatusTip("")
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setStyleSheet("color:rgb(255, 255, 255)")
        self.toolBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 12pt \"Arial\";")
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionCopyToClipboard_1 = QtWidgets.QAction(MainWindow)
        self.actionCopyToClipboard_1.setCheckable(True)
        self.actionCopyToClipboard_1.setObjectName("actionCopyToClipboard_1")
        self.actionCopyToClipboard_2 = QtWidgets.QAction(MainWindow)
        self.actionCopyToClipboard_2.setCheckable(True)
        self.actionCopyToClipboard_2.setObjectName("actionCopyToClipboard_2")
        self.actionCopyToClipboard_3 = QtWidgets.QAction(MainWindow)
        self.actionCopyToClipboard_3.setCheckable(True)
        self.actionCopyToClipboard_3.setObjectName("actionCopyToClipboard_3")
        self.actionAboutAuthor = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/bk_pic/gongzhonghao.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/bk_pic/about-self.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAboutAuthor.setIcon(icon1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionAboutAuthor.setFont(font)
        self.actionAboutAuthor.setObjectName("actionAboutAuthor")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/bk_pic/sharing.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon2)
        self.actionConnect.setObjectName("actionConnect")
        self.toolBar.addAction(self.actionAboutAuthor)
        self.toolBar.addAction(self.actionConnect)

        self.retranslateUi(MainWindow)
        self.CopyButton_1.clicked.connect(self.actionCopyToClipboard_1.trigger)
        self.ClearButton_1.clicked.connect(self.EditBox_1.clear)
        self.ClearButton_2.clicked.connect(self.EditBox_2.clear)
        self.ClearButton_3.clicked.connect(self.EditBox_3.clear)
        self.CopyButton_2.clicked.connect(self.EditBox_2.copy)
        self.CopyButton_3.clicked.connect(self.EditBox_3.copy)
        self.CopyButton_1.clicked.connect(self.EditBox_1.copy)
        self.CopyButton_2.clicked.connect(self.actionCopyToClipboard_2.trigger)
        self.CopyButton_3.clicked.connect(self.actionCopyToClipboard_3.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.EditBox_1, self.EditBox_2)
        MainWindow.setTabOrder(self.EditBox_2, self.EditBox_3)
        MainWindow.setTabOrder(self.EditBox_3, self.CopyButton_1)
        MainWindow.setTabOrder(self.CopyButton_1, self.ClearButton_1)
        MainWindow.setTabOrder(self.ClearButton_1, self.CopyButton_2)
        MainWindow.setTabOrder(self.CopyButton_2, self.ClearButton_2)
        MainWindow.setTabOrder(self.ClearButton_2, self.CopyButton_3)
        MainWindow.setTabOrder(self.CopyButton_3, self.ClearButton_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clipboard Share"))
        self.CopyButton_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Copy to Clipboard(<span style=\" color:#0000ff;\">CTRL+1</span>)</p></body></html>"))
        self.CopyButton_1.setText(_translate("MainWindow", "Copy", "Copy to Clipboard"))
        self.CopyButton_1.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.CopyButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Copy to Clipboard(<span style=\" color:#0000ff;\">CTRL+2</span>)</p></body></html>"))
        self.CopyButton_2.setText(_translate("MainWindow", "Copy", "Copy to Clipboard"))
        self.CopyButton_2.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.CopyButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Copy to Clipboard(<span style=\" color:#0000ff;\">CTRL+3</span>)</p></body></html>"))
        self.CopyButton_3.setText(_translate("MainWindow", "Copy", "Copy to Clipboard"))
        self.CopyButton_3.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.ClearButton_1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Clear this Edit Box</p></body></html>"))
        self.ClearButton_1.setText(_translate("MainWindow", "Clear", "Copy to Clipboard"))
        self.ClearButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Clear this Edit Box</p></body></html>"))
        self.ClearButton_2.setText(_translate("MainWindow", "Clear", "Copy to Clipboard"))
        self.ClearButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Clear this Edit Box</p></body></html>"))
        self.ClearButton_3.setText(_translate("MainWindow", "Clear", "Copy to Clipboard"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCopyToClipboard_1.setText(_translate("MainWindow", "CopyToClipboard"))
        self.actionCopyToClipboard_2.setText(_translate("MainWindow", "CopyToClipboard"))
        self.actionCopyToClipboard_3.setText(_translate("MainWindow", "CopyToClipboard"))
        self.actionAboutAuthor.setText(_translate("MainWindow", "About"))
        self.actionAboutAuthor.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/bk_pic/gongzhonghao.jpg\"/></p></body></html>"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">Connect another</span></p></body></html>"))

import bk_pic_rc
